### PR TITLE
build ripgrep package when there is no releases on github-releases

### PR DESCRIPTION
**Pull request by LongHanVisazure**
Changes: build the ripgrep package from source when failed to download binary file

Prerequisite: rust build environment.

### CODE REVIEW

**Comment by roblourens** [comment]
Why do you need this?

**Comment by LongHanVisazure** [comment]
I want to use vscode on nvidia tx2, I have to build from source code and blocked on vscode-ripgrep.

**Comment by roblourens** [comment]
I'm not sure I want to take this because it complicates things... can I just build and publish rg for your platform? What architecture does the nvidia tx2 use?

**Comment by LongHanVisazure** [comment]
Sure, it is welcome to build a special release of rg. 
The nvidia tx2 is an embedded platform from NVIDIA. It is an quad core ARM 64 cpu with powerful nvidia gpu. Command `uname` gives the info like Linux tegra-ubuntu 4.4.38-tegra , and the arch is  aarch64.
Then vendor's site is https://developer.nvidia.com/embedded/develop/hardware
By the way, I think it is better to provide a way to build rg by the vscode-ripgrep, as there should always be some special platform that you haven't covered.

**Comment by roblourens** [comment]
I do publish aarch64 as arm64, can you tell me the value of (in node) `process.env.npm_config_arch` and `require('os').arch()`?

**Comment by LongHanVisazure** [comment]
they are `undefined` and `arm64`

**Comment by roblourens** [comment]
And `os.platform()` is linux, right? It should download the arm64 build then. Can you share the logs from running `npm install vscode-ripgrep`? I'm curious at what point it fails.

**Comment by LongHanVisazure** [comment]
Sorry, It passed building this time. Thanks and sorry for your time.

**Pull request closed without merging**
